import { User } from "./types";

export const mockUsers: User[] = [
  {
    id: 1,
    name: "さくら",
    age: 25,
    gender: "female",
    city: "東京",
    image: require("./assets/profiles/profile1.jpg"),
    isOnline: true,
    isLiked: false,
  },
  {
    id: 2,
    name: "あやか",
    age: 29,
    city: "大阪",
    image: require("./assets/profiles/profile2.jpg"),
    gender: "female",
    isLiked: true,
  },
  {
    id: 3,
    name: "ゆい",
    age: 27,
    city: "京都",
    image: require("./assets/profiles/profile3.jpg"),
    isOnline: true,
    gender: "female",
    isLiked: true,
  },
  {
    id: 4,
    name: "みか",
    age: 26,
    city: "横浜",
    image: require("./assets/profiles/profile4.jpg"),
    gender: "female",
    isLiked: true,
  },
  {
    id: 5,
    name: "えみ",
    age: 24,
    city: "名古屋",
    image: require("./assets/profiles/profile5.jpg"),
    isOnline: true,
    gender: "female",
    isLiked: true,
  },
  {
    id: 6,
    name: "りな",
    age: 31,
    city: "神戸",
    image: require("./assets/profiles/profile6.jpg"),
    gender: "female",
    isLiked: true,
  },
  {
    id: 7,
    name: "まい",
    age: 26,
    city: "福岡",
    image: require("./assets/profiles/profile7.jpg"),
    gender: "female",
    isLiked: true,
  },
  {
    gender: "female",
    isLiked: true,
    id: 8,
    name: "なな",
    age: 25,
    city: "札幌",
    image: require("./assets/profiles/profile8.jpg"),
    isOnline: true,
  },
];
